Fix ie ratio
OVVE/software-ui pull request #86
Opened 2020-05-04 22:27 UTC by BrianWoodruff

I think this works based on simulation but I would like to see it running on hardware before merging.

2020-05-04 23:23 UTC, noelpaz requested changes
I tried to fix some changes in in_packet.py -- I think self was omitted. I am getting thinks like:

NameError: name 'ie_fixed_to_fraction' is not defined  

Around line 94

Then the function eie_fixed_to_fraction  n in_packet.py was complaining of a ZeroDivision error and I thin it need a try catch as well as converting literal ints into float for 1 to 1.0 for ex

After that back t comms_link.py it complained of some issues with Settings property

2020-05-04 23:40 UTC, noelpaz approved these changes

2020-05-05 00:11 UTC, mrrosen commented
From what I can see, it looks like it should work

2020-05-05 00:11 UTC, mrrosen approved these changes

2020-05-05 00:12 UTC, avigupta33 commented
This looks like it should work to me

2020-05-05 00:12 UTC, avigupta33 approved these changes

2020-05-05 00:14 UTC, merged